### ISSUE TITLE
invalid input params for task pack-builder: param types don't match the user-specified type: [PACK_CMD_FLAGS]

### ISSUE THREAD

**Issue by cmoulliard** [ch007m/pipeline-dsl-builder#19]
## Issue

The following generated parameter 
```
      - name: "PACK_CMD_FLAGS"
        value: "[$(params.packCmdBuilderFlags)]"
```
generates this error
```
[User error] Validation failed for pipelinerun pack-builder-push with error invalid input params for task pack-builder: param types don't match the user-specified type: [PACK_CMD_FLAGS]
```

It is fixed if we do this:
```
      - name: "PACK_CMD_FLAGS"
        value:
        - $(params.packCmdBuilderFlags)
        
or

      - name: "PACK_CMD_FLAGS"
        value: [$(params.packCmdBuilderFlags)]
```

Remark: This is certainly a Type related issue as we populate a string and not a Yaml array
