### ISSUE TITLE
Review how we specify the build type/task and group resources

### ISSUE THREAD

**Issue by cmoulliard** [ch007m/pipeline-dsl-builder#2]
## TODO

Review how we specify the build type and its task like also how we group the generated resources

Until now, we use the field `domain` to group the generated resources within the output folder
```
out/flows/build
out/flows/buildpack
etc
```
but also to tell to the tool which build action we would like to perform and indirectly which Tekton task we would like to use using the following YAML
```
job:
  # One of the supported resources: PipelineRun, Pipeline, Task
  resourceType: PipelineRun
  # The domain allows to specify for Konflux the type of the build-container - https://github.com/konflux-ci/build-definitions/blob/main/pipelines/template-build/template-build.yaml#L112
  # to be executed.
  # Such a type matches a corresponding Task which is either:
  # - pack: to build an image using the Pack CLI
  # - build: to build an application using a builder image
  # - builder: to create a builder image
  # - stack: to create a base stack image build or run
  # - meta/composite: to package the buildpacks of a "meta/composite" buildpack project
  # - buildpack: to package a "buildpack" project
  # - extension: to package an "extension" project
  domain: build
```

As you can see frm the previous list of types, we are mixing types which are not related and that will create confusion
