### ISSUE TITLE
Set default values for the volumeClaimTemplate or volumeClaim

### ISSUE THREAD

**Issue by cmoulliard** [ch007m/pipeline-dsl-builder#71]
## TODO

Set default values for the volumeClaimTemplate or volumeClaim
```
    - name: pack-workspace
      volumeClaimTemplate:
        storage: 1Gi
        accessMode: ReadWriteOnce
```
to
```
    - name: pack-workspace
      volumeClaimTemplate
```
