### ISSUE TITLE
Add volume and volumeMount support to the action when using script

### ISSUE THREAD

**Issue by cmoulliard** [ch007m/pipeline-dsl-builder#89]
## TODO

Add volume and volumeMount support to the action when using script

Example:
```
...
    image: quay.io/konflux-ci/buildah-task:latest@sha256:860a239c5f25376a435a514ae6d53a5c75b1fa492461d17774e9b7cb32d1e275
    name: build
    script: |-
      #!/bin/bash
      set -e
      set -o verbose
      mkdir -p ~/.ssh
      if [ -e "/ssh/error" ]; then
        #no server could be provisioned
        cat /ssh/error
        exit 1
      fi
      export SSH_HOST=$(cat /ssh/host)
...

    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
    - mountPath: /ssh
      name: ssh
      readOnly: true
  volumes:
  - name: etc-pki-entitlement
    secret:
      optional: true
      secretName: $(params.ENTITLEMENT_SECRET)
  - emptyDir: {}
    name: shared
  - configMap:
      items:
      - key: $(params.caTrustConfigMapKey)
        path: ca-bundle.crt
      name: $(params.caTrustConfigMapName)
      optional: true
    name: trusted-ca
  - emptyDir: {}
    name: varlibcontainers
  - emptyDir: {}
    name: workdir
  - name: ssh
    secret:
      optional: false
      secretName: multi-platform-ssh-$(context.taskRun.name)

```
